set(CMAKE_SYSTEM_NAME WASI)
set(CMAKE_SYSTEM_PROCESSOR wasm32)

find_program(WASIX_CC wasixcc REQUIRED)
find_program(WASIX_CXX_BASE wasixcc++ REQUIRED)
find_program(WASIX_AR wasixar REQUIRED)
find_program(WASIX_RANLIB wasixranlib REQUIRED)
find_program(WASIX_LD wasixld REQUIRED)
find_program(WASIX_NM wasixnm)
set(WASIX_C_WRAPPER "${CMAKE_CURRENT_LIST_DIR}/cmake/wasixcc-c")
set(WASIX_CXX_WRAPPER "${CMAKE_CURRENT_LIST_DIR}/cmake/wasixccxx-c++20")

set(CMAKE_C_COMPILER "${WASIX_C_WRAPPER}" CACHE FILEPATH "WASIX C compiler" FORCE)
set(CMAKE_CXX_COMPILER "${WASIX_CXX_WRAPPER}" CACHE FILEPATH "WASIX C++ compiler" FORCE)
set(CMAKE_AR "${WASIX_AR}" CACHE FILEPATH "WASIX archiver" FORCE)
set(CMAKE_RANLIB "${WASIX_RANLIB}" CACHE FILEPATH "WASIX ranlib" FORCE)
set(CMAKE_LINKER "${WASIX_LD}" CACHE FILEPATH "WASIX linker" FORCE)
if(WASIX_NM)
  set(CMAKE_NM "${WASIX_NM}" CACHE FILEPATH "WASIX nm" FORCE)
endif()

set(CMAKE_C_COMPILER_AR "${WASIX_AR}" CACHE FILEPATH "WASIX C compiler archiver" FORCE)
set(CMAKE_CXX_COMPILER_AR "${WASIX_AR}" CACHE FILEPATH "WASIX C++ compiler archiver" FORCE)
set(CMAKE_C_COMPILER_RANLIB "${WASIX_RANLIB}" CACHE FILEPATH "WASIX C compiler ranlib" FORCE)
set(CMAKE_CXX_COMPILER_RANLIB "${WASIX_RANLIB}" CACHE FILEPATH "WASIX C++ compiler ranlib" FORCE)

execute_process(
  COMMAND "${WASIX_C_WRAPPER}" --print-sysroot
  OUTPUT_VARIABLE WASIX_SYSROOT
  OUTPUT_STRIP_TRAILING_WHITESPACE
  ERROR_QUIET
)
if(WASIX_SYSROOT)
  set(CMAKE_SYSROOT "${WASIX_SYSROOT}" CACHE PATH "WASIX sysroot" FORCE)
  set(CMAKE_FIND_ROOT_PATH "${WASIX_SYSROOT}" CACHE PATH "WASIX root path" FORCE)
  set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
  set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
  set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
  set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
endif()

set(CMAKE_EXECUTABLE_SUFFIX ".wasm")
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)

# Inject WASIX shims for missing POSIX APIs used by libuv.
set(WASIX_COMPAT_HEADER "${CMAKE_CURRENT_LIST_DIR}/src/wasix_compat.h")
set(WASIX_COMPAT_INCLUDE "${CMAKE_CURRENT_LIST_DIR}/cmake/wasix-compat-include")
set(CMAKE_C_FLAGS_INIT
  "${CMAKE_C_FLAGS_INIT} -D_GNU_SOURCE -D_WASI_EMULATED_MMAN -D_WASI_EMULATED_SIGNAL -D_WASI_EMULATED_PROCESS_CLOCKS -include ${WASIX_COMPAT_HEADER} -isystem ${WASIX_COMPAT_INCLUDE}")
set(CMAKE_CXX_FLAGS_INIT
  "${CMAKE_CXX_FLAGS_INIT} -D_GNU_SOURCE -D_WASI_EMULATED_MMAN -D_WASI_EMULATED_SIGNAL -D_WASI_EMULATED_PROCESS_CLOCKS -include ${WASIX_COMPAT_HEADER} -isystem ${WASIX_COMPAT_INCLUDE}")

# Keep linker selection explicit for both C and C++ link steps.
set(CMAKE_EXE_LINKER_FLAGS_INIT "-fuse-ld=wasixld")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "-fuse-ld=wasixld")
set(CMAKE_MODULE_LINKER_FLAGS_INIT "-fuse-ld=wasixld")
