#!/usr/bin/env python3

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path


NODE_DEPS_BUILTIN_ROOTS = (
    "undici",
    "acorn",
    "minimatch",
    "cjs-module-lexer",
    "amaro",
    "v8/tools",
)


def strip_builtin_extension(path: Path) -> str:
    text = path.as_posix()
    if text.endswith(".js"):
        return text[:-3]
    if text.endswith(".mjs"):
        return text[:-4]
    raise ValueError(f"unsupported builtin extension: {path}")


def make_raw_string_literal(text: str) -> str:
    delimiter = f"E{hashlib.sha256(text.encode('utf-8')).hexdigest()[:7]}"
    while f"){delimiter}\"" in text:
        delimiter += "_X"
    return f'R"{delimiter}({text}){delimiter}"'


def collect_builtin_entries(project_root: Path) -> list[dict[str, object]]:
    entries: list[dict[str, object]] = []

    lib_root = project_root / "node" / "lib"
    for path in sorted(lib_root.rglob("*.js")):
        relative_path = path.relative_to(lib_root)
        entries.append(
            {
                "id": strip_builtin_extension(relative_path),
                "relative_path": relative_path.as_posix(),
                "source": path.read_text(encoding="utf-8"),
                "is_internal_dep": False,
            }
        )

    deps_root = project_root / "node" / "deps"
    for dep_root in NODE_DEPS_BUILTIN_ROOTS:
        root = deps_root / dep_root
        if not root.exists():
            continue
        paths: list[Path]
        if root.is_file():
            paths = [root]
        else:
            paths = sorted(list(root.rglob("*.js")) + list(root.rglob("*.mjs")))
        for path in paths:
            relative_path = path.relative_to(deps_root)
            entries.append(
                {
                    "id": f"internal/deps/{strip_builtin_extension(relative_path)}",
                    "relative_path": relative_path.as_posix(),
                    "source": path.read_text(encoding="utf-8"),
                    "is_internal_dep": True,
                }
            )

    entries.sort(key=lambda entry: entry["id"])
    return entries


def render_header(entries: list[dict[str, object]]) -> str:
    lines = [
        "// This file is auto-generated by scripts/generate_builtin_catalog_header.py.",
        "#pragma once",
        "",
        "#include <array>",
        "#include <string_view>",
        "",
        "namespace builtin_catalog::generated {",
        "",
        "struct BuiltinEntry {",
        "  std::string_view id;",
        "  std::string_view relative_path;",
        "  std::string_view source;",
        "  bool is_internal_dep;",
        "};",
        "",
        f"inline const std::array<BuiltinEntry, {len(entries)}> kBuiltinEntries = {{",
    ]

    for entry in entries:
        lines.append(
            "    BuiltinEntry{"
            f'{make_raw_string_literal(entry["id"])}, '
            f'{make_raw_string_literal(entry["relative_path"])}, '
            f'{make_raw_string_literal(entry["source"])}, '
            f'{"true" if entry["is_internal_dep"] else "false"}'
            "},"
        )

    lines.extend(
        [
            "};",
            "",
            "}  // namespace builtin_catalog::generated",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--project-root", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()

    project_root = args.project_root.resolve()
    output = args.output.resolve()
    output.parent.mkdir(parents=True, exist_ok=True)

    entries = collect_builtin_entries(project_root)
    output.write_text(render_header(entries), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
