#ifndef SRC_EDGE_VERSION_H_
#define SRC_EDGE_VERSION_H_

#define EDGE_MAJOR_VERSION 0
#define EDGE_MINOR_VERSION 0
#define EDGE_PATCH_VERSION 0

#ifndef EDGE_STRINGIFY
#define EDGE_STRINGIFY(n) EDGE_STRINGIFY_HELPER(n)
#define EDGE_STRINGIFY_HELPER(n) #n
#endif

#define EDGE_VERSION_STRING EDGE_STRINGIFY(EDGE_MAJOR_VERSION) "." \
                           EDGE_STRINGIFY(EDGE_MINOR_VERSION) "." \
                           EDGE_STRINGIFY(EDGE_PATCH_VERSION)
#define EDGE_VERSION "v" EDGE_VERSION_STRING

#endif  // SRC_EDGE_VERSION_H_
